var DESIGN_W = 1000;
var DESIGN_H = 720;
var DEFAULT_STATION_ID = "72st";

var MTA = {
  water: "#dcecff",
  grid: "rgba(86, 116, 149, 0.15)",
  land: "rgba(246, 242, 231, 0.86)",
  park: "rgba(193, 214, 161, 0.36)",
  boroughText: "rgba(45, 63, 89, 0.43)",
  waterText: "rgba(69, 106, 151, 0.68)",
  black: "#111111",
  civicBlue: "#0039a6",
  blue: "#0039a6",
  red: "#ee352e",
  orange: "#ff6319",
  yellow: "#fccc0a",
  green: "#00933c",
  purple: "#b933ad",
  lime: "#6cbe45",
  brown: "#996633",
  gray: "#a7a9ac",
  white: "#ffffff",
};

var LENS_COPY = {
  rate: "Reading-rate view: station color signals estimated proficiency level.",
  need:
    "Support-need view: warmer station signals show greater intervention urgency.",
  ell:
    "English learner view: station color emphasizes multilingual support pressure.",
  income:
    "Income view: station color compares neighborhood economic context across corridors.",
};

var ROUTE_META = {
  1: "Broadway–7 Av Local",
  2: "7 Av Express",
  3: "7 Av Express",
  4: "Lexington Av Express",
  5: "Lexington Av Express",
  6: "Lexington Av Local",
  7: "Flushing Local / Express",
  A: "8 Av Express",
  C: "8 Av Local",
  E: "8 Av Local",
  B: "6 Av Express",
  D: "6 Av Express",
  F: "Queens Blvd / 6 Av Local",
  M: "Queens Blvd / 6 Av Local",
  G: "Crosstown Local",
  J: "Nassau St Local",
  Z: "Nassau St Express",
  N: "Broadway Express",
  Q: "Broadway Express",
  R: "Broadway Local",
  W: "Broadway Local",
  L: "14 St–Canarsie Local",
  SIR: "Staten Island Railway",
};

var routeGroups = [
  {
    labels: ["A", "C", "E"],
    color: MTA.blue,
    points: [
      [305, 38],
      [314, 150],
      [304, 290],
      [292, 430],
      [288, 560],
      [300, 720],
    ],
  },
  {
    labels: ["1", "2", "3"],
    color: MTA.red,
    points: [
      [362, 28],
      [372, 150],
      [360, 290],
      [352, 430],
      [350, 560],
      [360, 720],
    ],
  },
  {
    labels: ["B", "D", "F", "M"],
    color: MTA.orange,
    points: [
      [448, 28],
      [456, 190],
      [462, 340],
      [450, 470],
      [425, 595],
      [398, 720],
    ],
  },
  {
    labels: ["N", "Q", "R", "W"],
    color: MTA.yellow,
    points: [
      [625, 245],
      [535, 270],
      [490, 355],
      [474, 458],
      [505, 565],
      [590, 665],
      [648, 720],
    ],
  },
  {
    labels: ["4", "5", "6"],
    color: MTA.green,
    points: [
      [590, 36],
      [580, 160],
      [592, 310],
      [580, 455],
      [595, 595],
      [620, 720],
    ],
  },
  {
    labels: ["7"],
    color: MTA.purple,
    points: [
      [355, 356],
      [520, 356],
      [675, 356],
      [825, 352],
      [930, 352],
    ],
  },
  {
    labels: ["L"],
    color: MTA.gray,
    points: [
      [170, 540],
      [345, 540],
      [590, 540],
      [805, 540],
      [940, 548],
    ],
  },
  {
    labels: ["G"],
    color: MTA.lime,
    points: [
      [690, 310],
      [630, 425],
      [680, 560],
      [795, 690],
    ],
  },
  {
    labels: ["J", "Z"],
    color: MTA.brown,
    points: [
      [500, 470],
      [615, 452],
      [760, 460],
      [855, 486],
    ],
  },
  {
    labels: ["SIR"],
    color: MTA.blue,
    points: [
      [138, 520],
      [190, 625],
      [242, 720],
    ],
  },
];

var stations = [
  {
    id: "207st",
    name: "207 St",
    x: 306,
    y: 54,
    routes: ["A"],
    borough: "Manhattan",
    district: "District 6",
    type: "Northern corridor station",
    readingRate: 68,
    income: 66300,
    englishLearners: 15.6,
    gap: 7,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "Northern Manhattan stop with mid-high proficiency and elevated English learner share.",
  },
  {
    id: "168st",
    name: "168 St",
    x: 312,
    y: 90,
    routes: ["A", "C", "1"],
    borough: "Manhattan",
    district: "District 6",
    type: "Transfer station",
    readingRate: 64,
    income: 61200,
    englishLearners: 17.2,
    gap: 3,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "Important transfer area where literacy support could reach multiple school communities.",
  },
  {
    id: "145st",
    name: "145 St",
    x: 315,
    y: 130,
    routes: ["A", "B", "C", "D"],
    borough: "Manhattan",
    district: "District 5",
    type: "Transfer station",
    readingRate: 58,
    income: 54500,
    englishLearners: 13.4,
    gap: -3,
    supportNeed: "High",
    status: "Estimated",
    note: "Upper Manhattan transfer point with meaningful outreach potential.",
  },
  {
    id: "125st",
    name: "125 St",
    x: 360,
    y: 175,
    routes: ["1", "2", "3", "A", "B", "C", "D"],
    borough: "Manhattan",
    district: "District 5",
    type: "Major transfer zone",
    readingRate: 57,
    income: 52800,
    englishLearners: 12.4,
    gap: -4,
    supportNeed: "High",
    status: "Estimated",
    note:
      "Harlem corridor node with strong strategic value for outreach and intervention.",
  },
  {
    id: "72st",
    name: "72 St / Upper West Side",
    x: 355,
    y: 285,
    routes: ["1", "2", "3"],
    borough: "Manhattan",
    district: "District 3",
    type: "Local/express corridor",
    readingRate: 72,
    income: 91751,
    englishLearners: 8.2,
    gap: 11,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "Higher-performing Manhattan trunk stop with strong household income and lower English learner share.",
  },
  {
    id: "59st",
    name: "59 St–Columbus Circle",
    x: 348,
    y: 255,
    routes: ["A", "B", "C", "D", "1"],
    borough: "Manhattan",
    district: "District 3",
    type: "Transfer station",
    readingRate: 71,
    income: 90200,
    englishLearners: 8.7,
    gap: 10,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "High-visibility transfer stop linking west side and central city literacy corridors.",
  },
  {
    id: "timessq",
    name: "Times Sq–42 St",
    x: 500,
    y: 350,
    routes: ["1", "2", "3", "7", "N", "Q", "R", "W", "S"],
    borough: "Manhattan",
    district: "District 2",
    type: "Mega-transfer complex",
    readingRate: 60,
    income: 78700,
    englishLearners: 10.8,
    gap: -1,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "A symbolic city center. Ideal for comparing systemwide literacy flow and transfer-driven visibility.",
  },
  {
    id: "penn",
    name: "34 St–Penn Station",
    x: 354,
    y: 430,
    routes: ["1", "2", "3", "A", "C", "E"],
    borough: "Manhattan",
    district: "District 2",
    type: "Regional access hub",
    readingRate: 58,
    income: 73900,
    englishLearners: 11.3,
    gap: -3,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "Large access node that links city commuters with concentrated Midtown student movement.",
  },
  {
    id: "herald",
    name: "34 St–Herald Sq",
    x: 456,
    y: 470,
    routes: ["B", "D", "F", "M", "N", "Q", "R", "W"],
    borough: "Manhattan",
    district: "District 2",
    type: "Multi-line transfer",
    readingRate: 59,
    income: 75400,
    englishLearners: 10.1,
    gap: -2,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "Dense transfer point where multiple literacy corridors intersect in a small footprint.",
  },
  {
    id: "grandcentral",
    name: "Grand Central–42 St",
    x: 594,
    y: 350,
    routes: ["4", "5", "6", "7", "S"],
    borough: "Manhattan",
    district: "District 2",
    type: "Historic central hub",
    readingRate: 69,
    income: 85800,
    englishLearners: 9.4,
    gap: 8,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "Higher-performing central corridor with strong connectivity and a more advantaged district profile.",
  },
  {
    id: "unionsq",
    name: "14 St–Union Sq",
    x: 592,
    y: 540,
    routes: ["4", "5", "6", "L", "N", "Q", "R", "W"],
    borough: "Manhattan",
    district: "District 2",
    type: "Cross-city transfer node",
    readingRate: 63,
    income: 81100,
    englishLearners: 9.8,
    gap: 2,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "One of the best places to compare north-south and east-west literacy corridors.",
  },
  {
    id: "atlantic",
    name: "Atlantic Av–Barclays",
    x: 565,
    y: 610,
    routes: ["2", "3", "4", "5", "B", "D", "N", "Q", "R"],
    borough: "Brooklyn",
    district: "District 13",
    type: "Brooklyn mega-transfer",
    readingRate: 55,
    income: 64200,
    englishLearners: 13.1,
    gap: -6,
    supportNeed: "High",
    status: "Estimated",
    note:
      "Key Brooklyn transfer where multiple lines converge and district contrasts become visible.",
  },
  {
    id: "fordham",
    name: "Fordham Rd",
    x: 582,
    y: 108,
    routes: ["4", "B", "D"],
    borough: "The Bronx",
    district: "District 10",
    type: "Bronx corridor node",
    readingRate: 47,
    income: 43500,
    englishLearners: 18.8,
    gap: -14,
    supportNeed: "High",
    status: "Estimated",
    note:
      "Important Bronx corridor with lower literacy performance and higher student support pressure.",
  },
  {
    id: "pelham",
    name: "Pelham Bay Park",
    x: 705,
    y: 72,
    routes: ["6"],
    borough: "The Bronx",
    district: "District 11",
    type: "Terminal station",
    readingRate: 67,
    income: 70100,
    englishLearners: 10.3,
    gap: 6,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "Higher Bronx reading profile relative to some interior corridor stops.",
  },
  {
    id: "jackson",
    name: "Jackson Heights–Roosevelt Av",
    x: 820,
    y: 350,
    routes: ["7", "E", "F", "M", "R"],
    borough: "Queens",
    district: "District 30",
    type: "Queens transfer hub",
    readingRate: 56,
    income: 59500,
    englishLearners: 21.2,
    gap: -5,
    supportNeed: "High",
    status: "Estimated",
    note:
      "Multilingual Queens hub with strong transfer value and high English learner concentration.",
  },
  {
    id: "flushing",
    name: "Flushing–Main St",
    x: 930,
    y: 350,
    routes: ["7"],
    borough: "Queens",
    district: "District 25",
    type: "Terminal station",
    readingRate: 66,
    income: 68900,
    englishLearners: 24.5,
    gap: 5,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "Queens terminal with solid literacy outcomes despite a very multilingual district context.",
  },
  {
    id: "court",
    name: "Court Sq",
    x: 710,
    y: 405,
    routes: ["E", "G", "7", "M"],
    borough: "Queens",
    district: "District 30",
    type: "Interborough connector",
    readingRate: 64,
    income: 84200,
    englishLearners: 11.1,
    gap: 3,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "High-value connector between Queens and Manhattan literacy corridors.",
  },
  {
    id: "bedford",
    name: "Bedford Av",
    x: 720,
    y: 540,
    routes: ["L"],
    borough: "Brooklyn",
    district: "District 14",
    type: "Brooklyn local station",
    readingRate: 62,
    income: 77300,
    englishLearners: 9.6,
    gap: 1,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "Brooklyn corridor stop with rising literacy performance and moderate district advantage.",
  },
  {
    id: "bwayjct",
    name: "Broadway Junction",
    x: 700,
    y: 645,
    routes: ["A", "C", "J", "Z", "L"],
    borough: "Brooklyn",
    district: "District 19",
    type: "Outer-borough transfer hub",
    readingRate: 43,
    income: 41800,
    englishLearners: 12.2,
    gap: -18,
    supportNeed: "Very High",
    status: "Estimated",
    note: "One of the clearest high-need transfer sites in the network.",
  },
  {
    id: "jamaica",
    name: "Jamaica Center",
    x: 955,
    y: 555,
    routes: ["E", "J", "Z"],
    borough: "Queens",
    district: "District 28",
    type: "Southeast Queens hub",
    readingRate: 49,
    income: 47000,
    englishLearners: 16.9,
    gap: -12,
    supportNeed: "High",
    status: "Estimated",
    note:
      "Important eastern corridor with below-city reading outcomes and meaningful support demand.",
  },
  {
    id: "stgeorge",
    name: "St. George",
    x: 140,
    y: 515,
    routes: ["SIR"],
    borough: "Staten Island",
    district: "District 31",
    type: "Ferry / rail gateway",
    readingRate: 59,
    income: 70500,
    englishLearners: 7.1,
    gap: -2,
    supportNeed: "Moderate",
    status: "Estimated",
    note:
      "The borough gateway. Useful for showing how isolated systems still connect into the citywide picture.",
  },
  {
    id: "tottenville",
    name: "Tottenville",
    x: 242,
    y: 708,
    routes: ["SIR"],
    borough: "Staten Island",
    district: "District 31",
    type: "Terminal station",
    readingRate: 71,
    income: 92800,
    englishLearners: 4.8,
    gap: 10,
    supportNeed: "Low",
    status: "Estimated",
    note:
      "Southern Staten Island terminal with stronger district outcomes and lower language-support pressure.",
  },
];

var minorStops = [
  { name: "103 St", x: 358, y: 215, routes: ["1"], color: MTA.red },
  { name: "50 St", x: 350, y: 316, routes: ["1"], color: MTA.red },
  { name: "23 St", x: 352, y: 470, routes: ["1"], color: MTA.red },
  { name: "14 St", x: 350, y: 540, routes: ["1", "2", "3"], color: MTA.red },
  {
    name: "47–50 Sts",
    x: 452,
    y: 310,
    routes: ["B", "D", "F", "M"],
    color: MTA.orange,
  },
  {
    name: "Canal St",
    x: 540,
    y: 610,
    routes: ["N", "Q", "R", "W", "J", "Z"],
    color: MTA.yellow,
  },
  { name: "59 St", x: 590, y: 255, routes: ["4", "5", "6"], color: MTA.green },
  { name: "86 St", x: 585, y: 210, routes: ["4", "5", "6"], color: MTA.green },
  {
    name: "Myrtle Av",
    x: 760,
    y: 470,
    routes: ["J", "M", "Z"],
    color: MTA.brown,
  },
  { name: "Nassau Av", x: 660, y: 475, routes: ["G"], color: MTA.lime },
  { name: "1 Av", x: 655, y: 540, routes: ["L"], color: MTA.gray },
  { name: "Lorimer St", x: 780, y: 540, routes: ["L"], color: MTA.gray },
  { name: "Stapleton", x: 170, y: 575, routes: ["SIR"], color: MTA.blue },
  { name: "Great Kills", x: 205, y: 650, routes: ["SIR"], color: MTA.blue },
];

var lineStopOverlay = [
  { name: "Dyckman St", x: 307, y: 44, routes: ["1"], color: MTA.red },
  { name: "157 St", x: 319, y: 112, routes: ["1"], color: MTA.red },
  { name: "116 St", x: 358, y: 195, routes: ["1"], color: MTA.red },
  { name: "66 St", x: 352, y: 300, routes: ["1"], color: MTA.red },

  { name: "190 St", x: 308, y: 68, routes: ["A"], color: MTA.blue },
  { name: "163 St", x: 313, y: 102, routes: ["C"], color: MTA.blue },
  { name: "116 St", x: 315, y: 160, routes: ["B", "C"], color: MTA.blue },
  { name: "81 St", x: 324, y: 235, routes: ["B", "C"], color: MTA.blue },
  {
    name: "42 St–PABT",
    x: 335,
    y: 350,
    routes: ["A", "C", "E"],
    color: MTA.blue,
  },

  { name: "7 Av", x: 455, y: 265, routes: ["B", "D", "E"], color: MTA.orange },
  { name: "23 St", x: 450, y: 500, routes: ["F", "M"], color: MTA.orange },
  {
    name: "DeKalb Av",
    x: 600,
    y: 650,
    routes: ["B", "Q", "R"],
    color: MTA.yellow,
  },

  { name: "125 St", x: 582, y: 150, routes: ["4", "5", "6"], color: MTA.green },
  { name: "51 St", x: 592, y: 320, routes: ["6"], color: MTA.green },
  { name: "Astor Pl", x: 594, y: 500, routes: ["6"], color: MTA.green },
  {
    name: "Brooklyn Bridge",
    x: 600,
    y: 585,
    routes: ["4", "5", "6"],
    color: MTA.green,
  },

  { name: "Hudson Yards", x: 355, y: 356, routes: ["7"], color: MTA.purple },
  { name: "5 Av", x: 545, y: 356, routes: ["7"], color: MTA.purple },
  { name: "Vernon Blvd", x: 665, y: 356, routes: ["7"], color: MTA.purple },
  {
    name: "Queensboro Plaza",
    x: 760,
    y: 354,
    routes: ["7"],
    color: MTA.purple,
  },
  { name: "74 St–Broadway", x: 835, y: 352, routes: ["7"], color: MTA.purple },
  { name: "Mets–Willets", x: 895, y: 352, routes: ["7"], color: MTA.purple },

  { name: "8 Av", x: 170, y: 540, routes: ["L"], color: MTA.gray },
  { name: "6 Av", x: 345, y: 540, routes: ["L"], color: MTA.gray },
  { name: "3 Av", x: 615, y: 540, routes: ["L"], color: MTA.gray },
  { name: "Graham Av", x: 820, y: 542, routes: ["L"], color: MTA.gray },
  {
    name: "Myrtle–Wyckoff",
    x: 875,
    y: 546,
    routes: ["L", "M"],
    color: MTA.gray,
  },

  { name: "Greenpoint Av", x: 670, y: 390, routes: ["G"], color: MTA.lime },
  { name: "Metropolitan", x: 680, y: 560, routes: ["G", "L"], color: MTA.lime },
  {
    name: "Hoyt–Schermerhorn",
    x: 750,
    y: 610,
    routes: ["G", "A", "C"],
    color: MTA.lime,
  },

  {
    name: "Essex St",
    x: 555,
    y: 470,
    routes: ["J", "Z", "F", "M"],
    color: MTA.brown,
  },
  {
    name: "Marcy Av",
    x: 725,
    y: 455,
    routes: ["J", "Z", "M"],
    color: MTA.brown,
  },
  { name: "Crescent St", x: 835, y: 486, routes: ["J", "Z"], color: MTA.brown },

  { name: "Tompkinsville", x: 155, y: 545, routes: ["SIR"], color: MTA.blue },
  { name: "Eltingville", x: 220, y: 675, routes: ["SIR"], color: MTA.blue },
];

console.log("RTC data.js loaded:", {
  DESIGN_W: DESIGN_W,
  DESIGN_H: DESIGN_H,
  routes: routeGroups.length,
  stations: stations.length,
  overlayStops: lineStopOverlay.length,
});
